version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: database
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ab_test
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    volumes:
      - db_data:/var/lib/mysql

  backend: 
    build: ./Supermarket_Hot_Deals/backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  frontend:
    build: ./Supermarket_Hot_Deals/frontend
    container_name: frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    command: streamlit run app.py --server.address=0.0.0.0
    depends_on:
      - backend

  ds:
    build: ./Supermarket_Hot_Deals/ds
    container_name: ds
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root
    ports:
      - "8888:8888"
    volumes:
      - ./ds:/app
    depends_on:
      - db

volumes:
  db_data: